#!/bin/bash

read -p "App name (lowercase, letters, numbers, hyphen only): " APP_NAME

aws cloudformation create-stack --capabilities CAPABILITY_NAMED_IAM --stack-name ${APP_NAME}-email --template-body file://./email.json --parameters ParameterKey=ApplicationName,ParameterValue=$APP_NAME --output text

# wait for completion
aws cloudformation wait stack-create-complete --stack-name ${APP_NAME}-email --output text

# output the access key id
echo "Access Key ID:"
aws cloudformation describe-stacks --stack-name ${APP_NAME}-email --query 'Stacks[0].Outputs[?OutputKey==`SESUserAccessKeyId`].OutputValue' --output text 

# output the secret access key
SECRET_ARN=`aws cloudformation describe-stacks --stack-name ${APP_NAME}-email --query 'Stacks[0].Outputs[?OutputKey==\`SESUserSecretAccessKeyARN\`].OutputValue' --output text`
echo "Secret Access Key:"
aws secretsmanager get-secret-value --query 'SecretString' --output text --secret-id $SECRET_ARN
